name: Test
on:
  push:
    branches:
      - dev
      - main
      - master
      - feature
  pull_request:
    branches:
      - main
      - dev
      - master
      - feature

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
     # - name: Test and coverage
     #   run: npm run test
      - name: Run my action
        uses: yarn start
       
